# Generated by Django 4.0 on 2023-06-09 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients_contract_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='mobile',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='id_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clients_contract_event.contractmodel'),
        ),
    ]
