# Generated by Django 4.0 on 2023-06-12 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients_contract_event', '0002_alter_clientmodel_mobile_alter_clientmodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='compagny_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
