# Generated by Django 4.0 on 2023-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients_contract_event', '0005_alter_clientmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='payment_due',
            field=models.DateField(auto_now_add=True),
        ),
    ]
