# Generated by Django 4.0 on 2023-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients_contract_event', '0006_alter_contractmodel_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='payment_due',
            field=models.DateField(),
        ),
    ]
