# Generated by Django 4.0 on 2023-06-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_teammodel_mobile_alter_teammodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='compagny_name',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='sales_contact',
        ),
    ]
