# Generated by Django 4.0 on 2023-06-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_teammodel_compagny_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.rolemodel'),
        ),
    ]
