# Generated by Django 4.0 on 2023-06-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_teammodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.rolemodel'),
        ),
    ]
